### ISSUE TITLE
When i block one specific server, the ping on all of the other ones just skyrockets, how can i fix this?

### ISSUE THREAD

**Issue by Mvthii** [FN-FAL113/cs2-server-picker#40] opened 2024-02-19 20:05 UTC
So, i'm in SA and i wanna block the Sao Paulo servers, but when i do so, the ping on the other SA servers (Buenos Aires, Santiago and Lima) just skyrockets up until it's unplayable unless i unblock the Sao Paulo servers, what can i do about this?

**Comment by FN-FAL113** [comment] 2024-02-20 00:19
ping ingame or ping shown from the app?

**Comment by Mvthii** [comment] 2024-02-20 00:22
> ping ingame or ping shown from the app?

both, i go from like 60ms on Argentina and 85ms on Chile to 190-300, both ingame and in the app

**Comment by FN-FAL113** [comment] 2024-02-20 02:19
can you record a video by showing the pings from the app with before and after comparison.

**Comment by Mvthii** [comment] 2024-02-20 17:20
https://streamable.com/dg9v1r

now the pings on the app stay high, but the game gets affected only when i block Brazil, i think it's bc of some rerouting through Brazil or something like that

**Comment by FN-FAL113** [comment] 2024-02-21 01:04
Might be an isp problem or as you said rerouting. Can you send another video by blocking sao paolo and pinging from the server picker app instead of pinging ingame?

**Comment by FN-FAL113** [comment] 2024-02-21 04:14
I don't think I can help any further, pretty sure the app is not the cause of your ping issue but location might be a factor. I'd suggest you try with different ISP, turn off vpn and uninstall third party av

**Comment by FN-FAL113** [comment] 2024-02-21 12:39
Closing this for now, feel free to comment still.

**Closed by FN-FAL113** 2024-02-21 12:39 UTC
